### ISSUE TITLE
Cannot launch shell on windows

### ISSUE THREAD

**Issue by mbramson** [sivsushruth/consolex#4] opened 2016-04-26 23:31 UTC
Upon selected iex or any other option from the Launch pop-up, the shell states "Launch again
Reason : disconnected from shell, shell terminated.

Console outputs the following: 

```
$ mix consolex.server
Started listening on port 5984...

19:23:52.159 [error] Ranch listener :my_http_listener had connection process started with :cowboy_protocol:start_link/4 at #PID<0.241.0> exit with reason: {:badarg, [{:erlang, :++, ["C:\\Windows\\system32\\cmd.exe", '.exe'], []}, {:os, :verify_executable, 3, [file: 'os.erl', line: 146]}, {:os, :find_executable, 2, [file: 'os.erl', line: 126]}, {Porcelain.Driver.Basic, :find_executable, 2, [file: 'lib/porcelain/drivers/basic_driver.ex', line: 103]}, {Porcelain.Driver.Basic, :do_spawn, 4, [file: 'lib/porcelain/drivers/basic_driver.ex', line: 62]}, {Porcelain, :catch_throws, 1, [file: 'lib/porcelain.ex', line: 273]}, {Consolex.Shell, :start_port, 2, [file: 'lib/shell/shell.ex', line: 5]}]}


19:23:52.166 [error] Process #PID<0.244.0> raised an exception
** (ArgumentError) argument error
    :erlang.++("C:\\Windows\\system32\\cmd.exe", '.exe')
    (kernel) os.erl:146: :os.verify_executable/3
    (kernel) os.erl:126: :os.find_executable/2
    (porcelain) lib/porcelain/drivers/basic_driver.ex:103: Porcelain.Driver.Basic.find_executable/2
    (porcelain) lib/porcelain/drivers/basic_driver.ex:62: Porcelain.Driver.Basic.do_spawn/4
    (porcelain) lib/porcelain.ex:273: Porcelain.catch_throws/1
    (consolex) lib/shell/shell.ex:5: Consolex.Shell.start_port/2
```

**Comment by sivsushruth** [comment] 2016-04-27 01:53
@mbramson Thanks for letting me know.
It was caused by porcelain not able to run on windows.
I have removed it as a dependency and wrote an interface from scratch to interact with the shell
Fixed via https://github.com/sivsushruth/consolex/commit/bcb7a85fb7285c16b4806b1dfa91ffde4818cdd2 and subsequent commits

Let me know if it works now :)

**Closed as completed** 2016-04-27 02:04 UTC
